---

- name: Certbot apache python2 package is installed
  apt:
    pkg: python-certbot-apache
    state: present
  when: ansible_distribution_version in ["16.04", "18.04"]

- name: Certbot apache python3 package is installed
  apt:
    pkg: python3-certbot-apache
    state: present
  when: ansible_distribution_version in ["20.04"]

- set_fact: certbot_plugin="--apache"
