---

- name: Certbot nginx python2 package is installed
  apt:
    pkg: python-certbot-nginx
    state: present
  when: ansible_distribution_version in ["16.04", "18.04"]

- name: Certbot nginx python3 package is installed
  apt:
    pkg: python3-certbot-nginx
    state: present
  when: ansible_distribution_version in ["20.04"]

- set_fact: certbot_plugin="--nginx"
